<?php

namespace Database\Seeders;

use App\Models\Dokumen;
use Illuminate\Database\Seeder;

class DokumenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Hanya mengisi data dummy untuk tabel dokumens.
     */
    public function run(): void
    {
        $dummyDokumens = [
            // 1. Perencanaan & Pembangunan
            [
                'judul' => 'Rencana Strategis (Renstra) Kelurahan Kraksaan Wetan 2025–2029',
                'nomor_dokumen' => '050/01/RENSTRA/KW/2025',
                'kategori' => 'Perencanaan & Pembangunan',
                'subkategori' => 'Rencana Strategis',
                'deskripsi' => 'Dokumen Rencana Strategis (Renstra) Kelurahan Kraksaan Wetan periode lima tahunan memuat visi pembangunan, indikator kinerja utama, program prioritas sarana prasarana kewilayahan, serta sasaran pengentasan kemiskinan perkotaan.',
                'periode' => '5 Tahunan',
                'periode_ke' => null,
                'file' => 'uploads/OuAmZcqeMhWXArN94MhvTWaf.pdf',
                'nama_file_asli' => 'Renstra_Kelurahan_Kraksaan_Wetan_2025_2029.pdf',
                'ukuran_file' => '2.4 MB',
                'tahun' => '2025',
                'tahun_selesai' => '2029',
                'diunduh' => 48,
                'aktif' => true,
                'tanggal_publikasi' => '2025-01-15',
            ],
            [
                'judul' => 'Rencana Kerja Pemerintah Kelurahan (RKP Kelurahan) Tahun 2026',
                'nomor_dokumen' => '050/04/RKP/KW/2026',
                'kategori' => 'Perencanaan & Pembangunan',
                'subkategori' => 'Rencana Kerja',
                'deskripsi' => 'Penjabaran operasional tahunan program pembangunan kelurahan tahun anggaran 2026 yang mengintegrasikan usulan aspirasi warga hasil Musrenbangkel dengan prioritas pembangunan Kabupaten Probolinggo.',
                'periode' => 'Tahunan',
                'periode_ke' => null,
                'file' => 'uploads/OuAmZcqeMhWXArN94MhvTWaf.pdf',
                'nama_file_asli' => 'RKP_Kelurahan_Kraksaan_Wetan_2026.pdf',
                'ukuran_file' => '1.8 MB',
                'tahun' => '2026',
                'tahun_selesai' => null,
                'diunduh' => 32,
                'aktif' => true,
                'tanggal_publikasi' => '2026-01-10',
            ],
            [
                'judul' => 'Berita Acara & Matriks Prioritas Usulan Musrenbangkel Tahun 2026',
                'nomor_dokumen' => '050/11/BA-MUSRENBANG/KW/2026',
                'kategori' => 'Perencanaan & Pembangunan',
                'subkategori' => 'Musrenbangkel',
                'deskripsi' => 'Dokumen resmi kesepakatan berita acara musyawarah rencana pembangunan kelurahan (Musrenbangkel) Tahun 2026 yang dihadiri oleh delegasi RT/RW, tokoh masyarakat, LPM, dan PKK.',
                'periode' => 'Tahunan',
                'periode_ke' => null,
                'file' => 'uploads/OuAmZcqeMhWXArN94MhvTWaf.pdf',
                'nama_file_asli' => 'Berita_Acara_Musrenbangkel_Kraksaan_Wetan_2026.pdf',
                'ukuran_file' => '890 KB',
                'tahun' => '2026',
                'tahun_selesai' => null,
                'diunduh' => 19,
                'aktif' => true,
                'tanggal_publikasi' => '2026-02-05',
            ],

            // 2. Keuangan & Anggaran
            [
                'judul' => 'Dokumen Pelaksanaan Anggaran (DPA) Kelurahan Kraksaan Wetan TA 2026',
                'nomor_dokumen' => '900/01/DPA/KW/2026',
                'kategori' => 'Keuangan & Anggaran',
                'subkategori' => 'DPA Kelurahan',
                'deskripsi' => 'Rincian alokasi anggaran pendapatan, belanja pegawai, belanja barang/jasa operasional kantor, serta pagu anggaran belanja modal infrastruktur kelurahan tahun 2026.',
                'periode' => 'Tahunan',
                'periode_ke' => null,
                'file' => 'uploads/OuAmZcqeMhWXArN94MhvTWaf.pdf',
                'nama_file_asli' => 'DPA_Kelurahan_Kraksaan_Wetan_TA_2026.pdf',
                'ukuran_file' => '3.2 MB',
                'tahun' => '2026',
                'tahun_selesai' => null,
                'diunduh' => 54,
                'aktif' => true,
                'tanggal_publikasi' => '2026-01-08',
            ],
            [
                'judul' => 'Laporan Realisasi Anggaran (LRA) Semester I Tahun Anggaran 2026',
                'nomor_dokumen' => '900/35/LRA-S1/KW/2026',
                'kategori' => 'Keuangan & Anggaran',
                'subkategori' => 'Laporan Realisasi Anggaran',
                'deskripsi' => 'Laporan pertanggungjawaban penyerapan dan realisasi belanja kegiatan fisik dan non-fisik Kelurahan Kraksaan Wetan pada periode Semester I (Januari s/d Juni 2026).',
                'periode' => 'Semesteran',
                'periode_ke' => 'Semester I',
                'file' => 'uploads/OuAmZcqeMhWXArN94MhvTWaf.pdf',
                'nama_file_asli' => 'LRA_Semester_I_Tahun_2026.pdf',
                'ukuran_file' => '650 KB',
                'tahun' => '2026',
                'tahun_selesai' => null,
                'diunduh' => 27,
                'aktif' => true,
                'tanggal_publikasi' => '2026-07-12',
            ],
            [
                'judul' => 'Laporan Penyerapan Anggaran Triwulan I TA 2026',
                'nomor_dokumen' => '900/18/SERAP-TW1/KW/2026',
                'kategori' => 'Keuangan & Anggaran',
                'subkategori' => 'Penyerapan Anggaran',
                'deskripsi' => 'Rekapitulasi pencapaian serapan anggaran kelurahan triwulan pertama tahun 2026 mencakup pos belanja rutin administrasi dan honorarium kelembagaan RT/RW.',
                'periode' => 'Triwulanan',
                'periode_ke' => 'Triwulan I',
                'file' => 'uploads/OuAmZcqeMhWXArN94MhvTWaf.pdf',
                'nama_file_asli' => 'Laporan_Serapan_Triwulan_I_2026.pdf',
                'ukuran_file' => '420 KB',
                'tahun' => '2026',
                'tahun_selesai' => null,
                'diunduh' => 14,
                'aktif' => true,
                'tanggal_publikasi' => '2026-04-05',
            ],

            // 3. Pemerintahan & Administrasi
            [
                'judul' => 'Laporan Akuntabilitas Kinerja Instansi Pemerintah (LKjIP) Tahun 2025',
                'nomor_dokumen' => '800/03/LKJIP/KW/2026',
                'kategori' => 'Pemerintahan & Administrasi',
                'subkategori' => 'Laporan Kinerja',
                'deskripsi' => 'Laporan resmi LKjIP yang memuat pengukuran capaian sasaran strategis, efisiensi penggunaan sumber daya, dan evaluasi target kinerja pelayanan tahun 2025.',
                'periode' => 'Tahunan',
                'periode_ke' => null,
                'file' => 'uploads/OuAmZcqeMhWXArN94MhvTWaf.pdf',
                'nama_file_asli' => 'LKjIP_Kelurahan_Kraksaan_Wetan_2025.pdf',
                'ukuran_file' => '1.9 MB',
                'tahun' => '2025',
                'tahun_selesai' => null,
                'diunduh' => 38,
                'aktif' => true,
                'tanggal_publikasi' => '2026-01-20',
            ],
            [
                'judul' => 'Buku Profil Kependudukan & Monografi Wilayah Tahun 2025',
                'nomor_dokumen' => '470/02/PROFIL/KW/2025',
                'kategori' => 'Pemerintahan & Administrasi',
                'subkategori' => 'Profil Kelurahan',
                'deskripsi' => 'Data statistik kewilayahan, komposisi penduduk menurut kelompok usia, mata pencaharian, batas teritorial lingkungan, dan sarana ibadah/pendidikan di Kraksaan Wetan.',
                'periode' => 'Tahunan',
                'periode_ke' => null,
                'file' => 'uploads/OuAmZcqeMhWXArN94MhvTWaf.pdf',
                'nama_file_asli' => 'Buku_Profil_Kependudukan_Kraksaan_Wetan_2025.pdf',
                'ukuran_file' => '4.1 MB',
                'tahun' => '2025',
                'tahun_selesai' => null,
                'diunduh' => 61,
                'aktif' => true,
                'tanggal_publikasi' => '2025-12-18',
            ],
            [
                'judul' => 'Laporan Bulanan Perkembangan Penduduk & Mutasi Warga (Januari 2026)',
                'nomor_dokumen' => '470/05/MUTASI-01/KW/2026',
                'kategori' => 'Pemerintahan & Administrasi',
                'subkategori' => 'Data Kelurahan',
                'deskripsi' => 'Laporan rekapitulasi peristiwa kependudukan bulanan meliputi kelahiran, kematian, pindah datang, dan pindah keluar pada bulan Januari 2026.',
                'periode' => 'Bulanan',
                'periode_ke' => 'Januari',
                'file' => 'uploads/OuAmZcqeMhWXArN94MhvTWaf.pdf',
                'nama_file_asli' => 'Laporan_Mutasi_Kependudukan_Januari_2026.pdf',
                'ukuran_file' => '310 KB',
                'tahun' => '2026',
                'tahun_selesai' => null,
                'diunduh' => 11,
                'aktif' => true,
                'tanggal_publikasi' => '2026-02-02',
            ],

            // 4. Pelayanan Publik
            [
                'judul' => 'Standar Pelayanan & Maklumat Pelayanan Publik Kelurahan Kraksaan Wetan',
                'nomor_dokumen' => '060/01/SPP/KW/2026',
                'kategori' => 'Pelayanan Publik',
                'subkategori' => 'Standar Pelayanan',
                'deskripsi' => 'Buku standar pelayanan publik memuat jenis layanan administrasi surat menyurat, persyaratan berkas, alur pengurusan, waktu penyelesaian, dan biaya pelayanan (gratis).',
                'periode' => 'Tahunan',
                'periode_ke' => null,
                'file' => 'uploads/OuAmZcqeMhWXArN94MhvTWaf.pdf',
                'nama_file_asli' => 'Standar_Pelayanan_Publik_Kraksaan_Wetan_2026.pdf',
                'ukuran_file' => '1.1 MB',
                'tahun' => '2026',
                'tahun_selesai' => null,
                'diunduh' => 79,
                'aktif' => true,
                'tanggal_publikasi' => '2026-01-05',
            ],
            [
                'judul' => 'Paket Blangko Formulir Pelayanan Administrasi Kependudukan',
                'nomor_dokumen' => '470/10/BLANGKO/KW/2026',
                'kategori' => 'Pelayanan Publik',
                'subkategori' => 'Formulir Layanan',
                'deskripsi' => 'Kumpulan blangko formulir resmi siap cetak untuk pengurusan Surat Pengantar Nikah (N1-N4), Keterangan Domisili Usaha, Keterangan Tidak Mampu (SKTM), dan Keterangan Ahli Waris.',
                'periode' => 'Sewaktu-waktu',
                'periode_ke' => null,
                'file' => 'uploads/OuAmZcqeMhWXArN94MhvTWaf.pdf',
                'nama_file_asli' => 'Blangko_Formulir_Pelayanan_Kelurahan.pdf',
                'ukuran_file' => '450 KB',
                'tahun' => '2026',
                'tahun_selesai' => null,
                'diunduh' => 115,
                'aktif' => true,
                'tanggal_publikasi' => '2026-01-02',
            ],
            [
                'judul' => 'Laporan Hasil Survei Kepuasan Masyarakat (SKM / IKM) Triwulan IV 2025',
                'nomor_dokumen' => '060/92/SKM-TW4/KW/2025',
                'kategori' => 'Pelayanan Publik',
                'subkategori' => 'Laporan Pelayanan',
                'deskripsi' => 'Hasil evaluasi survei kepuasan masyarakat terhadap kecepatan, keramahan petugas loket, dan transparansi pengurusan surat keterangan di kantor kelurahan dengan nilai indeks mutu A (Sangat Baik).',
                'periode' => 'Triwulanan',
                'periode_ke' => 'Triwulan IV',
                'file' => 'uploads/OuAmZcqeMhWXArN94MhvTWaf.pdf',
                'nama_file_asli' => 'Hasil_SKM_Triwulan_IV_2025.pdf',
                'ukuran_file' => '780 KB',
                'tahun' => '2025',
                'tahun_selesai' => null,
                'diunduh' => 22,
                'aktif' => true,
                'tanggal_publikasi' => '2026-01-12',
            ],

            // 5. Kegiatan & Kemasyarakatan
            [
                'judul' => 'Laporan Pelaksanaan Program Pemberdayaan Ekonomi Kreatif & UMKM 2025',
                'nomor_dokumen' => '500/14/PEMBD-UMKM/KW/2025',
                'kategori' => 'Kegiatan & Kemasyarakatan',
                'subkategori' => 'Pemberdayaan Masyarakat',
                'deskripsi' => 'Laporan realisasi kegiatan pelatihan pemasaran produk digital dan fasilitasi legalitas Nomor Induk Berusaha (NIB) bagi 50 pelaku usaha mikro di Kelurahan Kraksaan Wetan.',
                'periode' => 'Tahunan',
                'periode_ke' => null,
                'file' => 'uploads/OuAmZcqeMhWXArN94MhvTWaf.pdf',
                'nama_file_asli' => 'Laporan_Pemberdayaan_UMKM_2025.pdf',
                'ukuran_file' => '1.5 MB',
                'tahun' => '2025',
                'tahun_selesai' => null,
                'diunduh' => 29,
                'aktif' => true,
                'tanggal_publikasi' => '2025-11-20',
            ],
            [
                'judul' => 'Laporan Kegiatan Bulan Bhakti Gotong Royong Masyarakat (BBGRM) 2025',
                'nomor_dokumen' => '411/08/BBGRM/KW/2025',
                'kategori' => 'Kegiatan & Kemasyarakatan',
                'subkategori' => 'Kegiatan Kemasyarakatan',
                'deskripsi' => 'Dokumentasi dan laporan hasil kerja bakti terpadu normalisasi saluran drainase, pembersihan lingkungan RW, dan penghijauan kawasan permukiman warga.',
                'periode' => 'Tahunan',
                'periode_ke' => null,
                'file' => 'uploads/OuAmZcqeMhWXArN94MhvTWaf.pdf',
                'nama_file_asli' => 'Laporan_BBGRM_Kraksaan_Wetan_2025.pdf',
                'ukuran_file' => '2.1 MB',
                'tahun' => '2025',
                'tahun_selesai' => null,
                'diunduh' => 17,
                'aktif' => true,
                'tanggal_publikasi' => '2025-10-30',
            ],

            // 6. Transparansi & Akuntabilitas
            [
                'judul' => 'Laporan Penyelenggaraan Pemerintahan Kelurahan (LPPD) Akhir TA 2025',
                'nomor_dokumen' => '100/02/LPPD/KW/2026',
                'kategori' => 'Transparansi & Akuntabilitas',
                'subkategori' => 'Laporan Pertanggungjawaban',
                'deskripsi' => 'Laporan komprehensif pertanggungjawaban kinerja kepala kelurahan kepada Camat Kraksaan dan Bupati Probolinggo terkait pelaksanaan urusan pemerintahan wajib dan pilihan tahun 2025.',
                'periode' => 'Tahunan',
                'periode_ke' => null,
                'file' => 'uploads/OuAmZcqeMhWXArN94MhvTWaf.pdf',
                'nama_file_asli' => 'LPPD_Kelurahan_Kraksaan_Wetan_TA_2025.pdf',
                'ukuran_file' => '2.7 MB',
                'tahun' => '2025',
                'tahun_selesai' => null,
                'diunduh' => 43,
                'aktif' => true,
                'tanggal_publikasi' => '2026-02-15',
            ],
            [
                'judul' => 'Ringkasan Transparansi Anggaran & Realisasi Belanja Kelurahan TA 2025',
                'nomor_dokumen' => '900/50/INFO-ANGG/KW/2026',
                'kategori' => 'Transparansi & Akuntabilitas',
                'subkategori' => 'Informasi Anggaran',
                'deskripsi' => 'Infografis dan rekapitulasi data transparansi keuangan publik mengenai penerimaan dana kelurahan, efisiensi operasional, dan penyaluran insentif kader posyandu serta RT/RW.',
                'periode' => 'Tahunan',
                'periode_ke' => null,
                'file' => 'uploads/OuAmZcqeMhWXArN94MhvTWaf.pdf',
                'nama_file_asli' => 'Ringkasan_Transparansi_Anggaran_2025.pdf',
                'ukuran_file' => '1.2 MB',
                'tahun' => '2025',
                'tahun_selesai' => null,
                'diunduh' => 64,
                'aktif' => true,
                'tanggal_publikasi' => '2026-01-28',
            ],
        ];

        foreach ($dummyDokumens as $item) {
            Dokumen::firstOrCreate(
                ['nomor_dokumen' => $item['nomor_dokumen']],
                $item
            );
        }
    }
}
